// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uygoman.DATA;

namespace uygoman.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("uygoman.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("UserID")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("uygoman.Models.CompanyReg", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CmpArabicName");

                    b.Property<string>("CmpBrandName");

                    b.Property<string>("CmpName")
                        .IsRequired();

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("Upload");

                    b.Property<string>("UploadFileName");

                    b.HasKey("ID");

                    b.ToTable("CompanyRegs");
                });

            modelBuilder.Entity("uygoman.Models.CrKey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Keys")
                        .IsRequired();

                    b.Property<string>("Product_Name");

                    b.HasKey("ID");

                    b.HasIndex("Product_Name");

                    b.ToTable("CrKeys");
                });

            modelBuilder.Entity("uygoman.Models.Product", b =>
                {
                    b.Property<string>("ProductName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30);

                    b.HasKey("ProductName");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("uygoman.Models.CrKey", b =>
                {
                    b.HasOne("uygoman.Models.Product", "Prod")
                        .WithMany()
                        .HasForeignKey("Product_Name");
                });
#pragma warning restore 612, 618
        }
    }
}
